<?php

// define("DSN", 'mysql:host=10.35.160.3;dbname=bricketc');
// define("DB_USERNAME", 'root');
// define("DB_PASSWORD", 'c3c1eOLNIez2FCrw');
define("DSN", 'mysql:host=localhost;dbname=kidiaree');
define("DB_USERNAME", 'root');
define("DB_PASSWORD", '');
define("ERR_PARAMS_INVALID", 'Parameters Invalid');
define("ERR_PARAMS_INVALID_EMAIL", 'Email Invalid');
define("ERR_NOT_FOUND", 'Not Found');
define("ERR_NOT_ACTIVE", 'Inactive User');
define("ERR_UNAUTHORIZED", 'Unauthorized');
define("ERR_INVALID_OTP", 'Invalid OTP');
define("ERR_ALREADY_ENROLLED", 'Already Enrolled');
define("ERR_ALREADY_EXIST", 'Already exist with the same name');
define("ERR_PAYMENT_NOT_VERIFIED", 'Payment Not Verified');
define("ERR_DUPLICATE", 'Duplicate Entry');
define("ERR_ALREADY_REDEEMED", 'Already Redeemed');
define("ERR_CAMPAIGN_ENDED", 'Campaign Ended');
define("ERR_BUCKET_FULL", 'All Coupons Consumed');
define("ERR_COURSE_NOT_AVAILABLE", 'Selected Course is not available in this Campaign');
define("TWO_COURSES_DISCOUNT", 15);
define("THREE_COURSES_DISCOUNT", 20);
define("TIME_ZONE", 'Asia/Calcutta');
define("CONSUMER_PIN_PASSWORD", 'BrickETC@123');
define("CONTACT_US_MAIL", 'webmaster@bricketc.com');
define("ADMIN_MAIL_ID", 'webmaster@bricketc.com');
define("CALENDLY_SLUG_APPOINTMENT", '30min');
define("CALENDLY_SLUG_LIVE_SESSION", 'bricketc-live-session');
define("GET_ANSWERS_LIMIT", 50);
define("GET_QUESTIONS_LIMIT", 50);
define("GET_SUBMISSIONS_LIMIT", 50);
define("GET_COUNSELLINGS_LIMIT", 50);
define("FREE_TRIAL_DAYS", 7);
define("RAZORPAY_KEY_ID", 'rzp_test_UpQ1DUJg9dBeeV');
define("RAZORPAY_KEY_SECRET", 'cqMcXoEU2ytJiT9Ue4909R8V');
define("RAZORPAY_CURRENCY_IND", 'INR');
define("RAZORPAY_CURRENCY_US", 'USD');
define("GOOGLE_APPLICATION_CREDENTIALS_PATH", 'GOOGLE_APPLICATION_CREDENTIALS=C:\Users\Anand Kamat\Downloads\bricketc-955ec0747e65.json');
define("MOBILE_MESSAGE_FORMAT", 'https://api-mapper.clicksend.com/http/v2/send.php?method=http&username=anand.k@megotechnologies.com&key=2CE8362F-AEE2-69AB-FA35-6CFC14EE99E7&to=[MOBILE]&message=[MESSAGE]');
define("MOBILE_OTP_MESSAGE", 'Your Login OTP for Kidairee. is [OTP].');
?> 